linter:
  rules:
    require_trailing_commas: true
    overridden_fields: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    empty_statements: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    no_logic_in_create_state: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_specify_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    empty_catches: true
    file_names: true
    library_names: true
    library_prefixes: true
    null_check_on_nullable_type_parameter: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    sort_constructors_first: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_raw_strings: true
    prefer_single_quotes: true
    always_put_control_body_on_new_line: true
