name: dropin
description: A new Flutter project.

publish_to: 'none'


version: 1.0.10+93

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  #  state management
  get: ^4.6.6
  get_storage: 2.1.1
  geolocator: ^10.1.1
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  dio: 5.4.0
  logger: ^2.0.2+1
  photo_view: ^0.14.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  country_picker: ^2.0.24

  animate_do: ^3.3.3
  google_maps_flutter: ^2.5.3
  flutter_slidable: ^3.0.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  file_picker: ^6.1.1
  intl: ^0.19.0
  url_launcher: ^6.2.4
  dropdown_button2: ^2.3.9
  mask_text_input_formatter: ^2.8.0
  geocoding: ^2.1.1
  flutter_inappwebview: ^6.0.0
  firebase_crashlytics: ^3.4.14
  grouped_list: ^5.1.2
  swipe_to: ^1.0.5
  image: ^4.1.7
  custom_marker: ^1.0.0
  # google_maps_cluster_manager: ^3.0.0+1
  connectivity_plus: ^5.0.2
  image_cropper: 5.0.1
  syncfusion_flutter_charts: ^24.2.4+3
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  csv: ^5.1.1
  path_provider: ^2.1.2
  universal_html: ^2.2.4
  permission_handler: ^11.3.0
  excel: ^4.0.2
  fluttertoast: ^8.2.4
  # flutter_background_service: ^5.0.1
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.3.2
  smartrefresh: ^0.0.2
  uuid: ^4.3.3
  number_pagination: ^0.0.3+2
  cloud_functions: ^4.6.5
  rxdart: ^0.27.7



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/country_icons/
    - assets/styles/
    - assets/images/auth/
    - assets/images/
    - assets/images/web/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf

        - asset: assets/font/Montserrat-ExtraBold.ttf

        - asset: assets/font/Montserrat-Bold.ttf

        - asset: assets/font/Montserrat-SemiBold.ttf

        - asset: assets/font/Montserrat-Medium.ttf
        - asset: assets/font/Montserrat-Light.ttf
        - asset: assets/font/Montserrat-ExtraLight.ttf
        - asset: assets/font/Montserrat-Thin.ttf
